# Generated by Django 3.0.10 on 2022-06-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechRev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_of_technologies', models.CharField(blank=True, choices=[('Laboratory', 'Laboratory'), ('Radiology', 'Radiology'), ('Microbiology', 'Microbiology'), ('Others', 'Others')], max_length=30, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('eth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
