# Generated by Django 3.2.13 on 2022-07-02 08:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('institution_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30, verbose_name='Your Name')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=20, verbose_name='Your Title')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('institution_address', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30, verbose_name='Section/Unit/Derpartment')),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('sector_your_instution_belongs', models.CharField(blank=True, choices=[('HLI', 'HLI'), ('R&D', 'R&D'), ('Company', 'Company'), ('Regulatory', 'Regulatory'), ('Others', 'Others')], max_length=30, null=True, verbose_name='To which sector does your institution belong (e.g. HLI or R&D or Company)')),
                ('other_institution_belong', models.CharField(blank=True, max_length=500, null=True)),
                ('category_of_institution', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=50, null=True, verbose_name='To which of the categories does your institution fall?')),
                ('mandate_of_institution', models.CharField(blank=True, choices=[('Treatment/Prevention', 'Treatment/Prevention'), ('Research', 'Research'), ('Manufacturing', 'Manufacturing'), ('Others', 'Others')], max_length=50, null=True, verbose_name='What is the mandate of your institution')),
                ('other_mandate_of_institution', models.CharField(blank=True, max_length=500, null=True)),
                ('is_mvp', models.BooleanField(default=False)),
                ('is_svp', models.BooleanField(default=False)),
                ('is_spo', models.BooleanField(default=False)),
                ('is_rev', models.BooleanField(default=False)),
                ('is_drcp', models.BooleanField(default=False)),
                ('is_mgt', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
