# Generated by Django 3.0.10 on 2022-06-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
