# Generated by Django 3.0.10 on 2022-06-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mandate_of_institution',
            field=models.CharField(blank=True, choices=[('Treatment/Prevention', 'Treatment/Prevention'), ('Research', 'Research'), ('Manufacturing', 'Manufacturing'), ('Others', 'Others')], max_length=50, null=True, verbose_name='What is the mandate of your institution'),
        ),
    ]
