# Generated by Django 3.2.13 on 2022-07-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220704_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dpn',
            field=models.BooleanField(default=False, verbose_name='no'),
        ),
        migrations.AddField(
            model_name='user',
            name='qtwo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Are you resposible for adding equipment to the database?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_drcp',
            field=models.BooleanField(default=False, verbose_name='Others (specify)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mvp',
            field=models.BooleanField(default=False, verbose_name='yes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_rev',
            field=models.BooleanField(default=False, verbose_name='Microbiology'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_spo',
            field=models.BooleanField(default=False, verbose_name='Radiology'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_svp',
            field=models.BooleanField(default=False, verbose_name='Laboratory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='quetion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='which sector doeas your institution/organazation belongs to'),
        ),
    ]
